development:
  adapter:  postgresql 
  database: region8848
  username: dbuser 
  password: password 
  encoding: utf8
  host: localhost
  pool: 5

production:
  adapter:  postgresql 
  database: region8848
  username: dbuser 
  password: password 
  encoding: utf8
  host: localhost
  pool: 5

test:
  adapter:  postgresql 
  database: region8848
  username: dbuser 
  password: password 
  encoding: utf8
  host: localhost
  pool: 5
