# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2 
  database: region8848
  username: zhufeng
  password: 654321
  encoding: utf8
  host: localhost
  pool: 5

production:
  adapter: postgresql 
  database: d641t244mj5ur9 
  username: khetrhumklwejx 
  password: 1INp6ng2Iq1iTKIfykQpPjzeMY 
  encoding: utf8
  pool: 5
  host: ec2-54-197-241-94.compute-1.amazonaws.com
  port: 5432
